from importador import LinearModel

# a)
m1 = LinearModel('y', ['x2', 'x7', 'x8'], 'Liga_nacional_de_futbol.csv')
print('Resultados del modelo 1:')
print('------------------------')
print('Parametros estimados:')
print(m1.params, '\n')
# b)
print('Tabla ANOVA:')
print(m1.anov_t, '\n')
print('¿El modelo es significativo?')
print(m1.is_significant, '\n')
print('Resultado de la prueba F:')
print(m1.Ftest(), '\n')
# c)
print('Resultado de la prueba t para cada parámetro:')
print(m1.Ttest(), '\n')
# d)
print('R^2_values:')
print(m1.R2_values(), '\n')
# e)
print('QQ plot de los residuales:')
print(m1.qq_plot(show = False), '\n') #cambie show = True si quiere ver el grafico
# f)
print('Residuales contra valores ajustados:')
print(m1.residuals_vs_fitted(show = False), '\n') #cambie show = True si quiere ver el grafico
# g)
print('Residuales contra cada variable predictora:')
print(m1.residuals_vs_variables(show = False), '\n') #cambie show = True si quiere ver el grafico
# h)
print('Intervalos de 95% para los coeficientes de regresión:')
print(m1.IC_params())
print('Intervalos de 95% para la media de Y dado X = [2300, 56, 2100]:')
print(m1.IC_mean_y([2300, 56, 2100]))
print('-------------------------\n')
# i)
print('Resultados del modelo 2:')
print('------------------------')
m2 = LinearModel('y', ['x7', 'x8'], 'Liga_nacional_de_futbol.csv')
print('Parametros estimados:')
print(m2.params, '\n')
print('¿El modelo es significativo?')
print(m2.is_significant, '\n')
print('Resultado de la prueba F:')
print(m2.Ftest(), '\n')
# j)
print('R^2_values:')
print(m2.R2_values(), '\n')
# k)
print('Intervalos de 95% para los coeficientes de regresión:')
print(m2.IC_params())
print('Intervalos de 95% para la media de Y dado X = [56, 2100]:')
print(m2.IC_mean_y([56, 2100]))
print('-------------------------')